### ISSUE TITLE
Version 3 of Dataset

### ISSUE THREAD

**Issue by zara6697** [lindawangg/COVID-Net#111]
Dear all,
thanks for your code and dataset which are public. I have used version 3 of your dataset in my paper. according to reviewer comment I should do some test but I could not find version 3. could you help me how to access the data and the jupyter notebook file of split data of version 3?
Best Regards.

**Comment by haydengunraj** [comment]
Hi Zara, apologies for the late response and I hope it isn't too late for this to be useful.

Due to changes in the source datasets we use, we've had to update the scripts to address the change. As a result, previous versions of the dataset notebooks may not work correctly with the current versions of the various data sources. To fix this, you can modify the old notebooks to accommodate the changes, or use previous versions of the source datasets ensure compatibility.

In your case, I would recommend finding the COVID-Net repo commit that you originally used, and then downloading the corresponding versions of the source datasets to match this commit. To do this, you could compare the COVID-Net commit date to the dates in the source data repos/Kaggle pages. This might be a bit of a pain, but I think it would be your best bet.

**Comment by zara6697** [comment]
> 
> 
> Hi Zara, apologies for the late response and I hope it isn't too late for this to be useful.
> 
> Due to changes in the source datasets we use, we've had to update the scripts to address the changes. As a result, previous versions of the dataset notebooks may not work correctly with the current versions of the various data sources. To fix this, you can modify the old notebooks to accommodate the changes, or use previous versions of the source datasets ensure compatibility.
> 
> In your case, I would recommend finding the COVID-Net repo commit that you originally used, and then downloading the corresponding versions of the source datasets to match this commit. To do this, you could compare the COVID-Net commit date to the dates in the source data repos/Kaggle pages. This might be a bit of a pain, but I think it would be your best bet.

thanks a lot for your reply. I would check the solution which you mentioned.
best regards.
