### ISSUE TITLE
Do I need to train the model "COVIDNet-CXR-Large"? or I can directly inference the model with inference.py script?

### ISSUE THREAD

**Issue by hellosami** [lindawangg/COVID-Net#48]
1. Do I need to train the model "COVIDNet-CXR-Large"? or I can directly inference the model with inference.py script?

2. What should be the inference's x-ray image dimension in pixel? and what should be the image's file size of the inference's image?

**Comment by crubb** [comment]
1. Inferences worked for me with the pre-trained model. Please note, that I had to download the model files separately from Google Drive, since the larger files were not automatically packaged into the .zip by Google.

2. +1 - Would be very interested in the best file format and dimension of the files to be inferred, as well.

**Comment by hellosami** [comment]
Hey crubb, thank for the quick reply. I am interested to know the name of the model you downloaded from google drive separately. And what is "variables.data-00000-of-00001" found in "COVIDNet-CXR-Large\savedModel\variables".

**Comment by crubb** [comment]
I downloaded every file from the shared folder to recreate the shared folder locally.
For the saved model please see https://www.tensorflow.org/guide/saved_model.

**Comment by hellosami** [comment]
Sorry for late, thank you so much!
